Refactor to spec
regen-network/cosmosd pull request #2
Opened 2019-09-11 15:42 UTC by ethanfrey

This implements all parts of the README except for the download functionality (will be a separate PR). Actually download code is writen (copied from original design), but not tested.

Includes unit test coverage for all elements, including argument pass through, responding to log lines, exiting properly on normal exit (no upgrade), and switching directories on the proper triggers, along with many sanity checks.

I would like to get a review on this and merge it in, before proceeding in two more directions:

* Thorough tests on the download functionality
* Manual integration tests with real blockchain daemons

2019-09-11 17:19 UTC, aaronc requested changes
This is great. Really well structured and I see that you've found creative ways to test otherwise hard to test things.

I requested a few minor changes and had a few questions, but other than that mostly looks good to go.

The one behavioral thing I'm still questioning is whether or not the upgrade manager should just simply launch new sub-processes for upgrades rather than exiting and waiting for systemd to restart the upgrade manager. I think a good compromise solution would be to add an additional config flag that controls whether it exists or keeps running on upgrades (I don't really care which is the default). Seems like it would be a relatively simple change and allow for both operational methods - in particular just testing out a blockchain running straight in my terminal which I often do for testing. What do you think of that approach?

2019-09-11 17:19 UTC, aaronc commented on args_test.go
> +// Note all tests use the / path separator for simplicity and will fail on windows.
Could we avoid the technical debt now and just use https://golang.org/pkg/path/filepath/#FromSlash ?

2019-09-11 17:19 UTC, aaronc commented on process.go
> +}
Could you add just a few more comments in this function explaining why you chose to use a mutex and wait group to accomplish this functionality? That will make it clearer for me as well as future people working on this code.

2019-09-11 17:19 UTC, aaronc commented on upgrade.go
> +// in a state the will make a proper restart
Grammar issue: `in a state the will make a proper restart`

2019-09-11 17:19 UTC, aaronc commented on args.go
> +	Download bool
Maybe rename this `AllowDownloadBinaries` or something that is a little clearer?

2019-09-11 17:19 UTC, aaronc commented on args.go
> +	if os.Getenv("DAEMON_DOWNLOAD") == "on" {
Ditto for the env var, how about `DAEMON_ALLOW_DOWNLOAD_BINARIES`?

2019-09-11 17:19 UTC, aaronc commented on upgrade_test.go
> +// TODO: test with download (and test all download functions)
Btw with go-getter you could test "downloads" with local files actually

2019-09-11 17:19 UTC, aaronc commented on scanner_test.go
> +func ExampleScanner() {
Is this used at all? Why keep here?

2019-09-12 09:03 UTC, ethanfrey commented on args_test.go
> +// Note all tests use the / path separator for simplicity and will fail on windows.
Ah, niceone. I did not know that and just wanted to use strings to test, instead of tons of filpath.Join(). I will update.

2019-09-12 09:06 UTC, ethanfrey commented on process.go
> +}
3 go routines all touching the same variables? Basically I want a return value from 3 threads... 

I will document a bit more and maybe we can simplify... if we just wait for the command to exit, and assume it will not print out the upgrade log line and exit within a microsecond or two later, maybe I can just run that sync and block on the command...

This was the trickiest part for me, as there are three conditions to end, and all need to be checked in different threads.

2019-09-12 09:06 UTC, ethanfrey commented on args.go
> +	if os.Getenv("DAEMON_DOWNLOAD") == "on" {
Sure, I took this from the README.
I will update names in both places.

2019-09-12 09:07 UTC, ethanfrey commented on upgrade_test.go
> +// TODO: test with download (and test all download functions)
Nice. I will try.
I was going to add some files to the repo and attempt to get them from github rawcontent.
But local files is a tighter test loop

2019-09-12 09:08 UTC, ethanfrey commented on scanner_test.go
> +func ExampleScanner() {
I was having issues with pipes and trying to debug it, trying out different setup (earlier pipe config caused the scanner to miss the prefix of every line for some odd reason - I then simplified it witha  few standard mods from io).

I can remove it.

2019-09-12 09:13 UTC, ethanfrey commented
> The one behavioral thing I'm still questioning is whether or not the upgrade manager should just simply launch new sub-processes for upgrades rather than exiting and waiting for systemd to restart the upgrade manager. I think a good compromise solution would be to add an additional config flag that controls whether it exists or keeps running on upgrades (I don't really care which is the default). Seems like it would be a relatively simple change and allow for both operational methods - in particular just testing out a blockchain running straight in my terminal which I often do for testing. What do you think of that approach?

I thought of this as well - and we can do something if LaunchProcess returns nil - meaning everything is okay - and then just run it again in a loop. Not hard to code.

My worry was all those stdin/stderr writers and pipes and i dunna about memory usage, so figured it is safest just to restart and get fresh connections everywhere.

But the option of another flag is a good idea. `DAEMON_RESTART=on` will cause auto restart in Run if LaunchProcess returns nil. Sounds good. If the binary crashes or the upgrade fails, it will exit. But if we just have successful upgrades, it will keep running.

I would like to start with this default off, like download, but maybe we can later make them default on and have to set them `off` explicitly. Once we have tested them more thoroughly - default settings are simplest for now.

2019-09-12 12:55 UTC, ethanfrey commented on process.go
> +}
Addressed this in 24e2ace

2019-09-12 13:00 UTC, ethanfrey commented
I addressed all pr comments except those on download.
I will add download functionality in a separate PR.

If you are okay with these changes, please approve and merge. Future PRs can be smaller and targeted. I prefer not to load more into this one.

2019-09-12 13:56 UTC, aaronc approved these changes

2019-09-12 13:57 UTC, merged