Auto download
regen-network/cosmosd pull request #3
Opened 2019-09-12 14:06 UTC by ethanfrey

This supports the "binaries" field in the info.

- [x] Test info parsing logic
- [x] Implement/Test downloading file, zipped file, zipped directory (bin/autod)
- [x] Test checksum enforcement
- [x] Document how to calculate proper checksum 
- [x] Implement/Test referral link (info has url -> json with binary lookup mapping)
- [x] Test seemless integration with DoUpgrade and LaunchProcess

2019-09-12 14:24 UTC, ethanfrey commented
Missing one feature (point to a json file that then points to the download binaries), but ready for review.

Also happy if you have time to manually test this with real binaries

2019-09-12 14:52 UTC, aaronc requested changes

2019-09-12 14:52 UTC, aaronc commented on upgrade.go
> +		err = getter.Get(path, url)
Maybe we should just support directories with a `bin/` folder? I thought we discussed and that was your preference. I guess it's fine to support both if you think there's a good idea, but how common will it really be to just gzip a binary as opposed to tgz a dir with a binary?

2019-09-12 14:52 UTC, aaronc commented on upgrade_test.go
> +			info:  "https://foo.bar/",
I think we should support the upgrade info containing a go-getter URL that points to JSON as opposed to embedded JSON. I think this will actually be a quite common use case as people are wanting to limit on-chain text in governance proposals.

I have even thought we could alternatively accept YAML or even Markdown with YAML frontmatter, but that's more complex and opens up security concerns with YAML. Let's stick with JSON for now and consider that for the future.

2019-09-12 19:33 UTC, ethanfrey commented on upgrade_test.go
> +			info:  "https://foo.bar/",
Yes. I agree that was the todo. This test will fail when that is implemented

2019-09-12 20:03 UTC, ethanfrey commented on upgrade.go
> +		err = getter.Get(path, url)
I kind of think a simple binary put on github will be normal. Zipped or unzipped.

I consider that we support the whole `/bin` and more style for complex installs but not the normal case.

I would allow both. If you wish I can switch the order, so it tries the directory install first?

2019-09-12 21:19 UTC, ethanfrey commented on upgrade_test.go
> +			info:  "https://foo.bar/",
Now extended and reference links work as they should (I think).

2019-09-12 21:21 UTC, ethanfrey commented
This should be complete now.

Take a look, especially at the revamped `GetDownloadURL` in `upgrade.go`
but also at the whole flow in `TestLaunchProcessWithDownloads` in `process_test.go`

2019-09-12 21:35 UTC, aaronc commented on upgrade.go
> +		err = getter.Get(path, url)
I think that would be the more common case. But it doesn't really matter right?

2019-09-13 02:17 UTC, aaronc approved these changes

2019-09-13 02:19 UTC, aaronc approved these changes

2019-09-13 11:26 UTC, merged